#!/usr/bin/env bash
# record_session.sh — capture a Go2 driving session to a rosbag2 for RL baselines
# and sim replay. Records joint states (lowstate), base pose/velocity
# (sportmodestate), the web-joystick command stream (/web_teleop) and the active
# drive mode (/web_control_mode), plus safety/context topics.
#
# The recording is read-only: it does NOT command the robot. Drive as usual
# (Unitree sport mode or the RL policy) from the web joystick while this runs.
#
# Usage:
#   ./record_session.sh --name flat_walk_01 --mode both --terrain "lab floor" \
#                       --notes "figure-8, comfortable pace"
#   ./record_session.sh --name perc_walk_01 --camera   # joints + camera in ONE bag
#
# --camera records the D435i (raw cloud + sim-matched /go2/height_scan) into the
# SAME bag as the joint states, so they are time-aligned. It needs the perception
# stack up first: ros2 launch go2_bringup real_perception.launch.py
# For camera-only sessions use record_camera.sh instead.
#
# Output: sessions/<UTCdate>_<name>/  containing the bag + session_metadata.yaml
#
# Post-process to a Parquet dataset with:
#   python3 src/go2_remote_viz/recording/bag_to_dataset.py \
#       sessions/<...>/bag  --out sessions/<...>/dataset.parquet
set -eo pipefail

WS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- args ------------------------------------------------------------------
SESSION_NAME="session"
DRIVE_MODE="both"          # sport | rl | both — recorded as a marker + metadata
TERRAIN=""
NOTES=""
EXTRA_TOPICS=""
WITH_CAMERA=0

usage() { grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --name)     SESSION_NAME="$2"; shift 2 ;;
    --mode)     DRIVE_MODE="$2";   shift 2 ;;
    --terrain)  TERRAIN="$2";      shift 2 ;;
    --notes)    NOTES="$2";        shift 2 ;;
    --camera)   WITH_CAMERA=1;     shift 1 ;;   # also record the D435i into this bag
    --topics)   EXTRA_TOPICS="$2"; shift 2 ;;   # space-separated extra topics
    -h|--help)  usage 0 ;;
    *) echo "[record] unknown arg: $1" >&2; usage 1 ;;
  esac
done

# ---- source ROS 2 + Unitree overlay (mirrors RL_start_remote_connection.sh) -
set +u
if [ -f /opt/ros/humble/setup.bash ]; then
  source /opt/ros/humble/setup.bash
elif [ -f /opt/ros/foxy/setup.bash ]; then
  source /opt/ros/foxy/setup.bash
else
  echo "[record] ❌ No ROS 2 setup.bash in /opt/ros" >&2; exit 1
fi

: "${HOME:=/home/unitree}"
for u in "$HOME/unitree_ros2/install/setup.bash" "$HOME/unitree_ros2/install/setup.sh"; do
  [ -f "$u" ] && { source "$u"; break; }
done
set -u

# DDS transport must match the robot / other nodes (see RL_start_remote_connection.sh).
export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-0}"
export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}"

# ---- topic set -------------------------------------------------------------
# Shared topic sets (JOINT_STATE_TOPICS, WEB_TOPICS, CAMERA_TOPICS) — single
# source of truth in recording/topics.sh.
source "$WS_DIR/src/go2_remote_viz/recording/topics.sh"
STATE_TOPICS="$JOINT_STATE_TOPICS"
TOPICS="$STATE_TOPICS $WEB_TOPICS $EXTRA_TOPICS"
if [ "$WITH_CAMERA" = "1" ]; then
  TOPICS="$TOPICS $CAMERA_TOPICS"
  echo "[record] camera enabled — needs real_perception.launch.py running (cloud=$GO2_CLOUD_TOPIC)"
fi

# ---- output dir + metadata -------------------------------------------------
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_DIR="$WS_DIR/sessions/${STAMP}_${SESSION_NAME}"
BAG_DIR="$OUT_DIR/bag"
mkdir -p "$OUT_DIR"

GIT_SHA="$(git -C "$WS_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"

# Static contract facts — single source of truth is go2_rl_policy_node.py.
cat > "$OUT_DIR/session_metadata.yaml" <<YAML
# Auto-generated by record_session.sh. Describes how to interpret the bag.
session:
  name: "${SESSION_NAME}"
  utc_start: "${STAMP}"
  drive_mode: "${DRIVE_MODE}"        # sport | rl | both (see /web_control_mode column)
  terrain: "${TERRAIN}"
  notes: "${NOTES}"
  operator: "${USER:-unknown}"
  git_sha: "${GIT_SHA}"
env:
  ros_domain_id: "${ROS_DOMAIN_ID}"
  rmw: "${RMW_IMPLEMENTATION}"
recorded_topics:
$(for t in $TOPICS; do echo "  - \"$t\""; done)
# --- deployment contract (must match training; mirror of go2_rl_policy_node.py) ---
contract:
  control_rate_hz: 50
  action_scale: 0.25
  kp: 25.0
  kd: 0.5
  # SDK joint index order of lowstate.motor_state[i] / lowcmd.motor_cmd[i]:
  sdk_joint_order:
    [FR_hip, FR_thigh, FR_calf, FL_hip, FL_thigh, FL_calf,
     RR_hip, RR_thigh, RR_calf, RL_hip, RL_thigh, RL_calf]
  # foot_force / foot_position index order (Unitree convention):
  foot_order: [FR, FL, RR, RL]
  q_default:
    FL_hip: 0.1
    RL_hip: 0.1
    FR_hip: -0.1
    RR_hip: -0.1
    FL_thigh: 0.8
    FR_thigh: 0.8
    RL_thigh: 1.0
    RR_thigh: 1.0
    FL_calf: -1.5
    FR_calf: -1.5
    RL_calf: -1.5
    RR_calf: -1.5
YAML

echo "[record] session dir : $OUT_DIR"
echo "[record] drive mode  : $DRIVE_MODE"
echo "[record] topics      : $TOPICS"

# ---- sanity check: are the key state topics present? -----------------------
LIVE="$(ros2 topic list 2>/dev/null || true)"
for req in $STATE_TOPICS; do
  echo "$LIVE" | grep -qx "$req" \
    || echo "[record] ⚠️  '$req' not currently published — bag will capture it only if it appears."
done

# ---- record ----------------------------------------------------------------
# ros2 bag subscribes to listed topics and records them when they appear;
# missing topics are harmless. Ctrl+C to stop.
echo "[record] starting rosbag2 → $BAG_DIR   (Ctrl+C to stop)"
ros2 bag record -o "$BAG_DIR" $TOPICS &
BAG_PID=$!

# Seed an initial drive-mode marker so the bag is self-describing even when the
# web app published /web_control_mode (latched) *before* recording began.
if [ "$DRIVE_MODE" != "both" ]; then
  sleep 2   # let rosbag2 finish subscribing before we publish the one-shot marker
  if kill -0 "$BAG_PID" 2>/dev/null; then
    ros2 topic pub -1 /web_control_mode std_msgs/msg/String "{data: '${DRIVE_MODE}'}" >/dev/null 2>&1 || true
  fi
fi

cleanup() { kill -INT "$BAG_PID" 2>/dev/null || true; wait "$BAG_PID" 2>/dev/null || true; }
trap cleanup INT TERM
wait "$BAG_PID"
echo "[record] ✅ stopped. Session saved to $OUT_DIR"
