#!/usr/bin/env bash
# record_camera.sh — standalone RealSense D435i recorder for the Go2.
#
# Records the camera as its OWN module (no joint states): the raw depth cloud
# (reprocessable) plus the sim-matched processed height scan /go2/height_scan
# (same 187-cell mask the rough policy trained on), RGB/intrinsics, and TF.
#
# Needs the perception stack up first (you have "driver only" — this brings up
# the pointcloud filter, /go2/camera namespace, TF and heightmap_node):
#     ros2 launch go2_bringup real_perception.launch.py
#
# To record camera TOGETHER with joint states in one time-aligned bag, use
# `record_session.sh --camera` instead of this script.
#
# Usage:
#   ./record_camera.sh --name stepfield_01 --terrain "cubic stepfield" --notes "slow"
#
# Output: sessions/<UTCdate>_<name>_camera/  (bag + camera_metadata.yaml)
set -eo pipefail

WS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- args ------------------------------------------------------------------
SESSION_NAME="camera"
TERRAIN=""
NOTES=""
EXTRA_TOPICS=""

usage() { grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --name)     SESSION_NAME="$2"; shift 2 ;;
    --terrain)  TERRAIN="$2";      shift 2 ;;
    --notes)    NOTES="$2";        shift 2 ;;
    --topics)   EXTRA_TOPICS="$2"; shift 2 ;;
    -h|--help)  usage 0 ;;
    *) echo "[record-cam] unknown arg: $1" >&2; usage 1 ;;
  esac
done

# ---- source ROS 2 + Unitree overlay (mirrors record_session.sh) ------------
set +u
if [ -f /opt/ros/humble/setup.bash ]; then
  source /opt/ros/humble/setup.bash
elif [ -f /opt/ros/foxy/setup.bash ]; then
  source /opt/ros/foxy/setup.bash
else
  echo "[record-cam] ❌ No ROS 2 setup.bash in /opt/ros" >&2; exit 1
fi
: "${HOME:=/home/unitree}"
for u in "$HOME/unitree_ros2/install/setup.bash" "$HOME/unitree_ros2/install/setup.sh"; do
  [ -f "$u" ] && { source "$u"; break; }
done
set -u

export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-0}"
export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}"

# ---- topic set (shared source of truth) ------------------------------------
source "$WS_DIR/src/go2_remote_connection/recording/topics.sh"
TOPICS="$CAMERA_TOPICS $EXTRA_TOPICS"

# ---- output dir + metadata -------------------------------------------------
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_DIR="$WS_DIR/sessions/${STAMP}_${SESSION_NAME}_camera"
BAG_DIR="$OUT_DIR/bag"
mkdir -p "$OUT_DIR"
GIT_SHA="$(git -C "$WS_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"

# Height-scan grid contract — mirror of go2_perception/heightmap_node.py and
# real_perception.launch.py. Lets the bag be interpreted (and matched to the
# sim rough policy's scan) without re-reading the launch file.
cat > "$OUT_DIR/camera_metadata.yaml" <<YAML
# Auto-generated by record_camera.sh.
session:
  name: "${SESSION_NAME}"
  utc_start: "${STAMP}"
  kind: "camera-only"
  terrain: "${TERRAIN}"
  notes: "${NOTES}"
  operator: "${USER:-unknown}"
  git_sha: "${GIT_SHA}"
env:
  ros_domain_id: "${ROS_DOMAIN_ID}"
  rmw: "${RMW_IMPLEMENTATION}"
recorded_topics:
$(for t in $TOPICS; do echo "  - \"$t\""; done)
camera:
  cloud_topic: "${GO2_CLOUD_TOPIC}"
  # D435i intrinsics live in go2_bringup/config/camera.yaml (single source of truth).
height_scan:                      # /go2/height_scan — the sim-matched mask
  topic: "/go2/height_scan"
  msg_type: "std_msgs/Float32MultiArray"
  # MUST match training RayCaster GridPatternCfg + heightmap_node params:
  size_m: [1.6, 1.0]
  resolution_m: 0.1
  grid: [17, 11]                  # n_x x n_y = 187 cells
  center_x_m: 0.6                 # grid shifted forward to where the D435i looks
  height_offset_m: 0.5
  value_convention: "(base_z - hit_z) - offset, clipped"
YAML

echo "[record-cam] session dir : $OUT_DIR"
echo "[record-cam] topics      : $TOPICS"

# ---- sanity check: perception stack up? ------------------------------------
LIVE="$(ros2 topic list 2>/dev/null || true)"
for req in "$GO2_CLOUD_TOPIC" /go2/height_scan; do
  echo "$LIVE" | grep -qx "$req" \
    || echo "[record-cam] ⚠️  '$req' not published — is real_perception.launch.py running?"
done

# ---- record ----------------------------------------------------------------
echo "[record-cam] starting rosbag2 → $BAG_DIR   (Ctrl+C to stop)"
ros2 bag record -o "$BAG_DIR" $TOPICS &
BAG_PID=$!
cleanup() { kill -INT "$BAG_PID" 2>/dev/null || true; wait "$BAG_PID" 2>/dev/null || true; }
trap cleanup INT TERM
wait "$BAG_PID"
echo "[record-cam] ✅ stopped. Session saved to $OUT_DIR"
